sudo: required
dist: trusty
language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export CI=false
script:
  - react-scripts build
deploy:
  provider: pages
  local_dir: build
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
branch: develop